version: '3.8'

services:
  ros2-dev:
    build: .
    container_name: ros2_dev
    ports:
      - "5900:5900"
    volumes:
      - ./src:/workspace/src
      - ./launch:/workspace/launch
      - ./config:/workspace/config
    environment:
      - DISPLAY=:1
      - LIBGL_ALWAYS_SOFTWARE=1
      - XDG_RUNTIME_DIR=/tmp/runtime-root
    stdin_open: true
    tty: true
    command: bash